#pragma once
// Extracted strings from digi.exe
#include <cstddef>
static const wchar_t* g_strings[] = {
    L"낅Q맘?",
    L"D0>A",
    L"ﾈ<g塹9",
    L"UYVY",
    L"YUY2",
    L"DXT1",
    L"DXT2",
    L"DXT3",
    L"DXT4",
    L"DXT5",
    L"AL16",
    L"AR16",
    L"¿d3d8d.dll",
    L"DebugSetMute",
    L"d3d8.dll",
    L"F텘Ao뮲B!0",
    L"풱oftware\\Microsoft\\Direct3D",
    L"DisableMMX",
    L"GenuineIntel",
    L"DisableD3DXPSGP",
    L"Application transferred too many scanlines",
    L"Invalid SOS parameters for sequential JPEG",
    L"Corrupt JPEG data: found marker 0x%02x instead of RST%d",
    L"Premature end of JPEG file",
    L"Warning: unknown JFIF revision number %d.%02d",
    L"Corrupt JPEG data: bad Huffman code",
    L"Corrupt JPEG data: premature end of data segment",
    L"Corrupt JPEG data: %u extraneous bytes before marker 0x%02x",
    L"Inconsistent progression sequence for component %d coefficient %d",
    L"Unknown Adobe color transform code %d",
    L"Obtained XMS handle %u",
    L"Freed XMS handle %u",
    L"Unrecognized component IDs %d %d %d, assuming YCbCr",
    L"Opened temporary file %s",
    L"Closed temporary file %s",
    L"Ss=%d, Se=%d, Ah=%d, Al=%d",
    L"Component %d: dc=%d ac=%d",
    L"Start Of Scan: %d components",
    L"Start of Image",
    L"Component %d: %dhx%dv q=%d",
    L"Start Of Frame 0x%02x: width=%u, height=%u, components=%d",
    L"Smoothing not supported with nonstandard sampling ratios",
    L"RST%d",
    L"At marker 0x%02x, recovery action %d",
    L"Selected %d colors for quantization",
    L"Quantizing to %d colors",
    L"Quantizing to %d = %d*%d*%d colors",
    L"%4u %4u %4u %4u %4u %4u %4u %4u",
    L"Unexpected marker 0x%02x",
    L"Skipping marker 0x%02x, length %u",
    L"with %d x %d thumbnail image",
    L"Unknown JFIF minor revision number %d.%02d",
    L"Warning: thumbnail image size does not match data length %u",
    L"JFIF APP0 marker, density %dx%d  %d",
    L"%3d %3d %3d %3d %3d %3d %3d %3d",
    L"End Of Image",
    L"Obtained EMS handle %u",
    L"Freed EMS handle %u",
    L"Define Restart Interval %u",
    L"Define Quantization Table %d  precision %d",
    L"Define Huffman Table 0x%02x",
    L"Define Arithmetic Table 0x%02x: 0x%02x",
    L"Unknown APP14 marker (not Adobe), length %u",
    L"Unknown APP0 marker (not JFIF), length %u",
    L"Adobe APP14 marker: version %d, flags 0x%04x 0x%04x, transform %d",
    L"Caution: quantization tables are too coarse for baseline JPEG",
    L"6a  7-Feb-96",
    L"Copyright (C) 1996, Thomas G. Lane",
    L"Write to XMS failed",
    L"Read from XMS failed",
    L"Image too wide for this implementation",
    L"Virtual array controller messed up",
    L"Unsupported marker type 0x%02x",
    L"Application transferred too few scanlines",
    L"Write failed on temporary file --- out of disk space?",
    L"Seek failed on temporary file",
    L"Read failed on temporary file",
    L"Failed to create temporary file %s",
    L"Invalid JPEG file structure: SOS before SOF",
    L"Invalid JPEG file structure: two SOI markers",
    L"Unsupported JPEG process: SOF type 0x%02x",
    L"Invalid JPEG file structure: missing SOS marker",
    L"Invalid JPEG file structure: two SOF markers",
    L"Cannot quantize to more than %d colors",
    L"Cannot quantize to fewer than %d colors",
    L"Cannot quantize more than %d color components",
    L"Insufficient memory (case %d)",
    L"Not a JPEG file: starts with 0x%02x 0x%02x",
    L"Quantization table 0x%02x was not defined",
    L"JPEG datastream contains no image",
    L"Huffman table 0x%02x was not defined",
    L"Backing store not supported",
    L"Requested feature was omitted at compile time",
    L"Not implemented yet",
    L"Invalid color quantization mode change",
    L"Scan script does not transmit all data",
    L"Cannot transcode due to multiple use of quantization table %d",
    L"Premature end of input file",
    L"Empty input file",
    L"Maximum supported image dimension is %u pixels",
    L"Missing Huffman code table entry",
    L"Huffman code size table overflow",
    L"Fractional sampling not implemented yet",
    L"Output file write error --- out of disk space?",
    L"Input file read error",
    L"Didn't expect more than one scan",
    L"Write to EMS failed",
    L"Read from EMS failed",
    L"Empty JPEG image (DNL not supported)",
    L"Bogus DQT index %d",
    L"Bogus DHT index %d",
    L"Bogus DHT counts",
    L"Bogus DAC value 0x%x",
    L"Bogus DAC index %d",
    L"Unsupported color conversion request",
    L"Too many color components: %d, max %d",
    L"CCIR601 sampling not implemented yet",
    L"Suspension not allowed here",
    L"Buffer passed to JPEG library is too small",
    L"Bogus virtual array access",
    L"JPEG parameter struct mismatch: library thinks size is %u, caller expects %u",
    L"Improper call to JPEG library in state %d",
    L"Invalid scan script at entry %d",
    L"Bogus sampling factors",
    L"Invalid progressive parameters at scan script entry %d",
    L"Invalid progressive parameters Ss=%d Se=%d Ah=%d Al=%d",
    L"Unsupported JPEG data precision %d",
    L"Invalid memory pool code %d",
    L"Sampling factors too large for interleaved scan",
    L"Wrong JPEG library version: library is %d, caller expects %d",
    L"Bogus marker length",
    L"Bogus JPEG colorspace",
    L"Bogus input colorspace",
    L"IDCT output block size %d not supported",
    L"Invalid component ID %d in SOS",
    L"Bogus buffer control mode",
    L"MAX_ALLOC_CHUNK is wrong, please fix",
    L"ALIGN_TYPE is wrong, please fix",
    L"Sorry, there are legal restrictions on arithmetic coding",
    L"Bogus message code %d",
    L"0123456789ABCDEF1.0.5",
    L"IHDR",
    L"IDAT",
    L"IEND",
    L"PLTE",
    L"gAMA",
    L"sRGB",
    L"tRNS",
    L"?蠱L?",
    L"AuthenticAMD",
    L"UnknownVendr",
    L"need dictionary",
    L"띐 n;^",
    L"콋|o/",
    L"j-=m",
    L"\\c厭Qkkbal",
    L"聰鳴eP冗",
    L"湲풃|댒廻",
    L"앞藥晶|!賞",
    L"落j쉅쫋뻍쯫셖쩯뷫",
    L"incompatible version",
    L"buffer error",
    L"insufficient memory",
    L"data error",
    L"stream error",
    L"file error",
    L"stream end",
    L"YZ|良똵",
    L"Direct3DCreate8",
    L"timeGetTime",
    L"WINMM.dll",
    L"DSOUND.dll",
    L"MFC42.DLL",
    L"__CxxFrameHandler",
    L"fclose",
    L"fread",
    L"fseek",
    L"fopen",
    L"_ftol",
    L"strstr",
    L"_mbsrchr",
    L"sprintf",
    L"fwrite",
    L"rand",
    L"_mbscmp",
    L"atoi",
    L"fprintf",
    L"printf",
    L"_EH_prolog",
    L"floor",
    L"_CIacos",
    L"_finite",
    L"exit",
    L"_CIasin",
    L"MSVCRT.dll",
    L"_except_handler3",
    L"?terminate@@YAXXZ",
    L"__dllonexit",
    L"_onexit",
    L"_exit",
    L"_XcptFilter",
    L"_acmdln",
    L"__getmainargs",
    L"_initterm",
    L"__setusermatherr",
    L"_adjust_fdiv",
    L"__p__commode",
    L"__p__fmode",
    L"__set_app_type",
    L"_controlfp",
    L"GetDriveTypeA",
    L"Sleep",
    L"DeleteFileA",
    L"MultiByteToWideChar",
    L"WideCharToMultiByte",
    L"LocalFree",
    L"IsDBCSLeadByte",
    L"LoadLibraryA",
    L"GetProcAddress",
    L"GetModuleHandleA",
    L"GetVersionExA",
    L"IsProcessorFeaturePresent",
    L"GetStartupInfoA",
    L"KERNEL32.dll",
    L"IntersectRect",
    L"UpdateWindow",
    L"MessageBoxA",
    L"PeekMessageA",
    L"PostMessageA",
    L"ShowWindow",
    L"GetFocus",
    L"GetAsyncKeyState",
    L"RedrawWindow",
    L"OffsetRect",
    L"GetMessageA",
    L"SetFocus",
    L"DispatchMessageA",
    L"TranslateMessage",
    L"AdjustWindowRect",
    L"ShowCursor",
    L"CloseWindow",
    L"CopyRect",
    L"DrawTextA",
    L"DrawTextW",
    L"USER32.dll",
    L"DeleteObject",
    L"GetTextMetricsA",
    L"CreateFontA",
    L"CreateCompatibleDC",
    L"GetTextExtentPoint32A",
    L"GetObjectA",
    L"CreateFontIndirectA",
    L"DeleteDC",
    L"SelectObject",
    L"SetTextColor",
    L"SetBkColor",
    L"SetBkMode",
    L"CreateDIBSection",
    L"GDI32.dll",
    L"RegCloseKey",
    L"RegQueryValueExA",
    L"RegOpenKeyA",
    L"ADVAPI32.dll",
    L"??1_Lockit@std@@QAE@XZ",
    L"??0_Lockit@std@@QAE@XZ",
    L"MSVCP60.dll",
    L"CoInitialize",
    L"CoUninitialize",
    L"CoCreateInstance",
    L"ole32.dll",
    L"_setmbcp",
    L"MAP\\MAP%d\\%s.MAP",
    L"MAP\\MAP%d\\%s.TFS",
    L"%s\\%.2d_%.2d.bmp",
    L"MAP\\CMAP\\MAP%d\\%s",
    L"%s\\MASK%.2d.bmp",
    L"MAP\\MMAP\\MAP%d\\%s",
    L"MAYO01",
    L"MAYO02",
    L"DMAYO03",
    L"MAYO04A",
    L"MAYO04B",
    L"MAYO05",
    L"MAYO06",
    L"MAYO11",
    L"MAYO10",
    L"MAYO08A",
    L"MAYO08B",
    L"TROP00",
    L"TROP01",
    L"TROP02",
    L"TROP03",
    L"TROP04",
    L"TROP05",
    L"TROP06",
    L"EMIHA00",
    L"MIHA01",
    L"MIHA02",
    L"MIHA03",
    L"MIHA04A",
    L"MIHA04B",
    L"TUNN01",
    L"TUNN02",
    L"TUNN03",
    L"TUNN04",
    L"TUNN05",
    L"TUNN06",
    L"TUNN07",
    L"TUNN08",
    L"TUNN09",
    L"TUNN10",
    L"DGHA01",
    L"DGHA02",
    L"GCAN01",
    L"GCAN02",
    L"GCAN03",
    L"GCAN04",
    L"GCAN05",
    L"GCAN06",
    L"GCAN07",
    L"GCAN08_1",
    L"GCAN09",
    L"OGRE00",
    L"OGRE01",
    L"OGRE02",
    L"OGRE03",
    L"GCAN11",
    L"YAKA02",
    L"YAKA11A",
    L"YAKA11B",
    L"YAKA12",
    L"YAKA13",
    L"YAKA14",
    L"YAKA15",
    L"YAKA16",
    L"YAKA17",
    L"YAKA18",
    L"YAKA22",
    L"YAKA23",
    L"YAKA24",
    L"CHKA01",
    L"SAIB01",
    L"SAIB02",
    L"GIAS00",
    L"GIAS01",
    L"GIAS02",
    L"GIAS03",
    L"GIAS04",
    L"GIAS05",
    L"GIAS06A",
    L"GIAS07",
    L"GIAS08",
    L"GIAS09",
    L"KODA00",
    L"KODA01",
    L"KODA02",
    L"KODA03",
    L"KODA04",
    L"!KODA05",
    L"!KODA06",
    L"!KODA07",
    L"!KODA08",
    L"!FRZL01",
    L"\"FRZL02",
    L"\"FRZL03",
    L"\"FRZL04",
    L"\"FRZL05",
    L"\"FRZL06",
    L"\"FRZL07",
    L"\"FRZL08",
    L"\"FRZL12",
    L"\"ICSA01",
    L"#ICSA02",
    L"#ICSA03",
    L"#ICSA04",
    L"#ICSA05",
    L"#ICSA06",
    L"#ICSA07",
    L"#ICSA08",
    L"#BETL01",
    L":BETL02",
    L":BETL03",
    L":BETL04",
    L":MAYO00",
    L"MAYO01_2",
    L"MAYO02_2",
    L"TRAI00",
    L"$LEOM01",
    L"%LEOM02",
    L"%MIST01",
    L"&MIST02",
    L"&MIST03",
    L"&MIST04",
    L"&MIST05",
    L"&MIST06",
    L"&MIST07",
    L"&TUNN07_2",
    L"TUNN07_3",
    L"TUNN08_2",
    L"TUNN08_3",
    L"TUNN03_2",
    L"GCAN04_2",
    L"'GCAN08_2",
    L"'GCAN10",
    L"'OGRE04",
    L"GIAS06B",
    L"FRZL13",
    L"(FRZL14",
    L"(FRZL15",
    L"(FRZL16",
    L"(FRZL17",
    L"(FRZL18",
    L"(STIC01",
    L")STIC02",
    L")GKYO01",
    L"*GKYO02",
    L"*OGRE10",
    L"3OGRE11",
    L"3OMOC01",
    L"2OMOC02",
    L">OMOC03",
    L"?OMOC04",
    L"=OMOC05",
    L"=OMOC06",
    L"=OMOC07",
    L"=OMOC08",
    L"=FACT01",
    L"4FACT02",
    L"4FACT03",
    L"4FACT04",
    L"4FACT05",
    L"4FACT06",
    L"4FACT07",
    L"4FACT08A",
    L"4FACT08B",
    L"4FACT09",
    L"4FACT10",
    L"4FACT11A",
    L"9GOMI01",
    L"8GOMI02",
    L"8MGEN01",
    L";MGEN02",
    L";TWNA02",
    L"+TWNA03",
    L"+TWNA04",
    L"+TWNA05",
    L"+TWNA06",
    L"+TWNA07",
    L"+TWNA08",
    L"+TWNA09",
    L"+TWNA10",
    L"+TWNA11",
    L"+TWNA12",
    L"+TWNA13",
    L"+TWNB01",
    L"+TWNB02",
    L"+TWNB03",
    L"+TWNB04",
    L"+TWNB05",
    L"+TWNB06",
    L"+TWNB07",
    L"+TWNB08",
    L"+TWNB09",
    L"+TWNB10",
    L"+TWNB11",
    L"+TWNB12",
    L"+TWNB13",
    L"+TWNB14",
    L"+TWNB15",
    L"+TWNB16",
    L"+TWNB17",
    L"+TWNB18",
    L"+TWNB19",
    L"+TWNB20",
    L"+TWNB21",
    L"+TWNB22",
    L"+TWNB23",
    L"+TWNB24",
    L"+TWNA01",
    L"+ROOM10",
    L"0ROOM11",
    L"0ROOM12",
    L"5ROOM13",
    L"6ROOM14",
    L"7MGEN03",
    L";ROOM02",
    L",MGEN04",
    L";ROOM04",
    L"-ROOM05A",
    L".ROOM05B",
    L".ROOM06",
    L"/ROOM07",
    L"1ROOM08",
    L"0MGEN05",
    L";FACT11B",
    L"9SAIB03",
    L"MGEN98",
    L";ROOM19",
    L"6YAKA26",
    L"MGEN99",
    L";MGEN11",
    L"CMGEN12",
    L"CMGEN13",
    L"CMGEN14",
    L";MGEN15",
    L";MGEN16",
    L";YAKA25",
    L"MIHA05",
    L"MIHA06",
    L"ROOM20",
    L"<TEND01",
    L"+TEND02",
    L"+TOPN01",
    L"MGEN06",
    L";MGEN07",
    L";MGEN08",
    L"MGEN09",
    L";MGEN10",
    L"선택의 숲",
    L"꿈틀몬의 보금자리",
    L"암흑 귀족의 저택 지하",
    L"암흑 귀족의 저택 천정 위",
    L"암흑 귀족의 저택 2층",
    L"로봇 하우스",
    L"인형 하우스",
    L"장난감 저택",
    L"디지몬 컬링장",
    L"무한마운틴",
    L"비트랜드",
    L"쓰레기 산",
    L"보물 찾기 집",
    L"투기장 로비",
    L"버드라 운송",
    L"팩토리얼 타운",
    L"비밀의 해안 동굴",
    L"장난감 거리",
    L"비밀 아이템 상점",
    L"할배몬의 집",
    L"아이템 상점",
    L"레스토랑",
    L"캔터스 의원",
    L"아이템 보관소",
    L"시작의 마을",
    L"다이온 촌",
    L"개골개골 습지",
    L"그레이트 캐넌",
    L"레오몬 선조의 동굴",
    L"그린 짐",
    L"아이스 생츄어리",
    L"프리즈 랜드",
    L"고대의 땅 다이노 - 시간이 빠르게 가는 지역",
    L"고대의 땅 다이노 - 시간이 느리게 가는 지역",
    L"고대의 땅 다이노 입구",
    L"기어 사반나",
    L"지하 실험장",
    L"암흑귀족의 저택 지하",
    L"암흑귀족의 저택",
    L"모노크로 상점",
    L"우가몬 요새",
    L"그레이트 캐넌 하층",
    L"요새 입구",
    L"그레 대교",
    L"그레이트 캐넌 상층",
    L"그레이트 캐넌 입구",
    L"오버델 묘지",
    L"용암동굴",
    L"두리몬의 숙소",
    L"드릴터널 지하 3층",
    L"드릴터널 지하 2층",
    L"드릴터널",
    L"전망대산 포자지역",
    L"전망대산기슭",
    L"시작의 마을 입구",
    L"전망대산 산길",
    L"망그로브 지역",
    L"트로피칼 정글",
    L"디지브릿지",
    L"드릴터널 입구",
    L"용의눈 호숫가",
    L"실러컨 해안",
    L"헤매지 않는 숲",
    L"대회 스케줄",
    L"디지몬 시디를 찾을 수 없습니다",
    L"Local AppWizard-Generated Applications",
    L"시디에러",
    L"이름 입력",
    L"일려나 카나 히데카즈 돌아오는 종료",
    L"너의 이름",
    L"디지몬의 이름",
    L"파피푸페포",
    L"바비부베보",
    L"다지두데도",
    L"자지주제조",
    L"가기구게고",
    L"라릴레로",
    L"마밈메모",
    L"하히후헤호",
    L"나니누네노",
    L"타치츠테토",
    L"사시스세소",
    L"카키쿠케코",
    L"っゃゅょ",
    L"ぁぃぅぇぉ",
    L"ぱぴぷぺぽ",
    L"마미 부 가 ぼ",
    L"이다ぢづ로 정도",
    L"자리 치질 그림 자",
    L"가 도리 속げ",
    L"들 유리 るれ 로",
    L"눈매 무 눈도",
    L"는 피부에 걸음",
    L"무엇ぬ 네노",
    L"칼 연줄과",
    L"구더기 스세 그것",
    L"나 묻는 けこ",
    L"아이우에오",
    L"%sSOUND\\sb.whb",
    L"%c:\\",
    L".wav",
    L".rmi",
    L".mid",
    L"ETCNA\\UNTI.TMD",
    L"Press Start Button",
    L"ETCNA\\title256.tim",
    L"movie\\op1.wmv",
    L"%s-%s",
    L"No Data",
    L"SAVE\\%d.sav",
    L"게  임  저  장",
    L"취  소",
    L"초기화면으로 돌아가시겠습니까?",
    L"저장하시겠습니까?",
    L"Save화일을 덮어 쓰시겠습니까?",
    L"초기화면으로 가시겠습니까?",
    L"초  기  화  면",
    L"저  장  하  기",
    L"%d FPS, MAPID : %d, MAPHEADID : %d  evoTime : %d scrX : %d, scrY : %d",
    L"Slot %d",
    L"movie\\op2.wmv",
    L"ETCNA\\title2.tim",
    L"%d FPS, MAPID : %d",
    L"CARD\\CARD.ALL",
    L"ETCDAT\\SLOT.TIM",
    L"ETCDAT\\ETCTIM.BIN",
    L"Back",
    L"Name",
    L"%sSOUND\\BGM\\FAALL_%.3d.sgt",
    L"삭제할 Slot선택",
    L"저장된 게임 선택",
    L"저장할 Slot선택",
    L"게 임 종 료",
    L"이 어 서 하 기",
    L"처 음 부 터 하 기",
    L"LTJLSP2002",
    L"CDWWnd",
    L"현재 그래픽 카드의 호환성이 디지몬을 실행하기에 부적합 합니다.",
    L"최신 그래픽 드라이버를 다시 설치하여 주신다음, 디지몬을 다시 실행하시기 바랍니다.",
    L"DirectX 에러",
    L"CHDAT\\MMD%d\\%s.MMD",
    L"그레이몬",
    L"+,.-*)",
    L"에어드라몬",
    L"티라노몬",
    L"시드라몬",
    L"메탈그레이몬",
    L"+,.-/(*)",
    L"캅테리몬",
    L"버드라몬",
    L"프리지몬",
    L"%&'$ \"",
    L"스컬그레이몬",
    L"+0.-/(*)",
    L"메탈콩알몬",
    L"베이더몬",
    L"+,/*",
    L"켄터스몬",
    L"안드로몬",
    L".-/(",
    L"%$ \"",
    L"모노크로몬",
    L"실러컨몬",
    L"메가드라몬",
    L"%&'#!$ \"",
    L"디지타몬",
    L"Ｈ캅테리몬",
    L".-/)%&'#!$ \"]ÿ",
    L"메가시드라몬",
    L"웨아갈루몬",
    L"화이트레오몬",
    L"기가드라몬",
    L"메탈에테몬",
    L"왕잠자리몬",
    L"화염리자몬",
    L"배드퍼펫몬",
    L"2./)",
    L"스노우아구몬",
    L"블루우가몬",
    L"화이트스카몬",
    L"독꿈틀몬",
    L"얼룩유니몬",
    L"레드베지몬",
    L"J모털몬",
    L"수염두리몬",
    L"고부리몬",
    L"머드프리지몬",
    L"사이케몬",
    L"투베타몬",
    L"토이아구몬",
    L"오로라몬",
    L"헬로우워메몬",
    L"버미리몬",
    L"그린쉘몬",
    L"가드로몬",
    L"레드펭귄몬",
    L"아이스몬",
    L"레드꼬끼몬",
    L"츄카이몬",
    L"원시고부리몬",
    L"쿠리아아구몬",
    L"그린베지몬",
    L"아이스데블몬",
    L"다크리자몬",
    L"왕모래잠자리몬",
    L"스노우고부리몬",
    L"블루메라몬",
    L"세이버드라몬",
    L"데블시드라몬",
    L"파워드라몬",
    L"아날로그맨",
    L"마켓가게 주인",
    L"왕개굴몬",
    L"스카몬 대왕",
    L"쥬레이몬",
    L"생철（blik） 인형",
    L"티라노 선생",
    L"브라키몬",
    L"페티메라몬",
    L"d.*)",
    L"d0./*",
    L"d,/*",
    L"묘티스몬",
    L"CEMG",
    L"CEGR",
    L"EVAN",
    L"EPEN",
    L"EIGA",
    L"EDIG",
    L"EPIC",
    L"EMGD",
    L"ENAN",
    L"EMOJ",
    L"EKUW",
    L"ECOC",
    L"ESIR",
    L"ELEO",
    L"EMNO",
    L"EPAL",
    L"EPIY",
    L"EETE",
    L"EGIR",
    L"EAND",
    L"ESCU",
    L"EDOR",
    L"EBAK",
    L"ECEN",
    L"ESHE",
    L"EOGR",
    L"EUNI",
    L"EKUN",
    L"EPAT",
    L"EVED",
    L"EMTM",
    L"ESKU",
    L"EVEG",
    L"EHOE",
    L"EYUK",
    L"EGAR",
    L"EBIR",
    L"EANG",
    L"EKAB",
    L"EELE",
    L"EGAB",
    L"EMON",
    L"EMAM",
    L"EMTG",
    L"ENUM",
    L"ESEA",
    L"EMER",
    L"ETYR",
    L"EAIR",
    L"EDEV",
    L"EGRE",
    L"EBET",
    L"PUTI",
    L"BRAK",
    L"EGOB",
    L"TIRS",
    L"BRIK",
    L"HAGU",
    L"JURE",
    L"SCUD",
    L"TONO",
    L"TENS",
    L"JIJI",
    L"ANLG",
    L"MUGE",
    L"tAKA",
    L"INSE",
    L"WRSE",
    L"TENT",
    L"GECO",
    L"OTAM",
    L"GOLE",
    L"SOUL",
    L"SABD",
    L"GRUR",
    L"BLMR",
    L"SNGB",
    L"SNDY",
    L"DKRZ",
    L"ICDV",
    L"ZASS",
    L"CLEA",
    L"SHAM",
    L"TUKA",
    L"AKAT",
    L"ICEM",
    L"MCHO",
    L"GARD",
    L"MRIS",
    L"TKKA",
    L"FUGA",
    L"VARM",
    L"GERE",
    L"ARUR",
    L"PIDD",
    L"TOYA",
    L"MODO",
    L"PSYC",
    L"TUTI",
    L"GOBR",
    L"NISE",
    L"JMOJ",
    L"REDV",
    L"TANK",
    L"SIMA",
    L"DOKU",
    L"PCSC",
    L"HYOG",
    L"YKAG",
    L"WARU",
    L"FLAR",
    L"GOTU",
    L"YANM",
    L"VAND",
    L"MTET",
    L"GGDR",
    L"PANJ",
    L"wEAG",
    L"MGSD",
    L"HKAB",
    L"HOUO",
    L"IGAM",
    L"PENM",
    L"DIGI",
    L"PICC",
    L"MGDR",
    L"NANI",
    L"MOJA",
    L"KUWA",
    L"COCA",
    L"SIRA",
    L"LEOM",
    L"MONO",
    L"PALM",
    L"PIYO",
    L"TANE",
    L"YURA",
    L"ETEM",
    L"GIRO",
    L"ANDR",
    L"SCUM",
    L"DORI",
    L"BAKE",
    L"CENT",
    L"SHEL",
    L"OGRE",
    L"UNIM",
    L"KUNE",
    L"PATA",
    L"TOKO",
    L"POYO",
    L"VEDA",
    L"MTMA",
    L"SKUL",
    L"VEGI",
    L"HOEE",
    L"YUKI",
    L"GARU",
    L"BIRD",
    L"ANGE",
    L"KABU",
    L"ELEC",
    L"GABU",
    L"TUNO",
    L"PUNI",
    L"MONZ",
    L"MAME",
    L"MTGR",
    L"NUME",
    L"SEAD",
    L"MERA",
    L"TYRA",
    L"AIRD",
    L"DEVI",
    L"GREY",
    L"BETA",
    L"AGUM",
    L"KORO",
    L"BOTA",
    L"BOYS",
    L"CHDAT\\ALLTIM.TIM",
    L"%s을 읽을 수 없습니다.",
    L"!\"#$%&",
    L"'()*+,-./01234567",
    L"*0&89:;<",
    L"=>?\"@A",
    L"$3:,",
    L"BCDE:F0",
    L"!\"#$%&'()*+,-./012438",
    L"SOUND\\sl.whb",
    L"SOUND\\ss.whb",
    L"SOUND\\VLALL\\VLALL-%d.WHB",
    L"SOUND\\VBALL\\VBALL-%d.WHB",
    L"SOUND\\SB.WHB",
    L"%*!4",
    L"%,<4",
    L"%)<4",
    L"0:!4",
    L".-04",
    L"STDDAT\\DRAW.TMD",
    L"STDDAT\\B_TOGI.ATR",
    L"STDDAT\\B_TOGI.TIM",
    L"STDDAT\\T_TOGI.TIM",
    L"STDDAT\\B_TOGI.TMD",
    L"STDDAT\\T_TOGI.TMD",
    L"STDDAT\\GRADE\\BT.TIM",
    L"STDDAT\\GRADE\\HU.TIM",
    L"STDDAT\\GRADE\\AN.TIM",
    L"STDDAT\\GRADE\\WI.TIM",
    L"STDDAT\\GRADE\\DY.TIM",
    L"STDDAT\\GRADE\\DT.TIM",
    L"STDDAT\\GRADE\\MT.TIM",
    L"STDDAT\\GRADE\\NT.TIM",
    L"STDDAT\\GRADE\\CO.TIM",
    L"STDDAT\\GRADE\\TW.TIM",
    L"STDDAT\\GRADE\\GP.TIM",
    L"STDDAT\\GRADE\\FR.TIM",
    L"STDDAT\\GRADE\\CAPVO.TIM",
    L"STDDAT\\GRADE\\CAPV4.TIM",
    L"STDDAT\\GRADE\\CAPV3.TIM",
    L"STDDAT\\GRADE\\CAPV2.TIM",
    L"STDDAT\\GRADE\\CAPV1.TIM",
    L"STDDAT\\GRADE\\GRADER.TIM",
    L"STDDAT\\GRADE\\GRADES.TIM",
    L"STDDAT\\GRADE\\GRADEA.TIM",
    L"STDDAT\\GRADE\\GRADEB.TIM",
    L"STDDAT\\GRADE\\GRADEC.TIM",
    L"STDDAT\\GRADE\\GRADED.TIM",
    L"STDDAT\\T_DAI.TMD",
    L"STDDAT\\B_DAI.TMD",
    L"STDDAT\\CHAMP.TMD",
    L"STDDAT\\TIME.TIM",
    L"STDDAT\\STDTIM.BIN",
    L"STDDAT\\WIN_LOSE.TMD",
    L"ETCHI\\EFEDAT.EFE",
    L"PPPnnnFFF",
    L"@@@pD,HT||Lh",
    L"MS PMincho",
    L",)E'A",
    L"곤충 컵",
    L"휴먼 컵",
    L"애니멀 컵",
    L"다이노 컵",
    L"더티 컵",
    L"메탈릭 컵",
    L"네이처 컵",
    L"선더윈드컵",
    L"그래플 컵",
    L"파이어 컵",
    L"버전Ｏ 컵",
    L"버전４ 컵",
    L"버전３ 컵",
    L"버전２ 컵",
    L"버전１ 컵",
    L"그레이드Ｒ",
    L"그레이드Ｓ",
    L"그레이드Ａ",
    L"그레이드Ｂ",
    L"그레이드Ｃ",
    L"그레이드Ｄ",
    L"SCN\\MAPHEAD.SCN",
    L"SCN\\DG.SCN",
    L"SCN\\convert.jk",
    L"ETCNA\\IWA1.TIM",
    L"ETCNA\\IWA.TMD",
    L"ETCNA\\HAKO.TMD",
    L"ETCNA\\DOSYA.TMD",
    L"ETCNA\\ABOX.TMD",
    L"ETCNA\\GAND.TMD",
    L"ETCHI\\OP.TIM",
    L"ETCHI\\BOSS_EFE.TMD",
    L"ETCDAT\\KARRING.TMD",
    L"NULL",
    L"현재BIT",
    L"가격 %d",
    L"정말 입니까?",
    L"%s카드",
    L"ETCNA\\T_YAMA.TMD",
    L"ETCDAT\\TAMA.tim",
    L"모으는 아이템",
    L"소지한 물건",
    L"맡긴 물건",
    L"설명을 듣는다",
    L"게임을 시작한다",
    L"「으으, 우리가 졌어...」",
    L"「헤헤헤, 우리의 승리다！」",
    L"「아직 승부는 이제부터야！」",
    L"「너는, 정말 별 볼 일이",
    L"우리의 승리로 한다！",
    L"「그리고, 무승부일 경우는",
    L"푸른 선의 안 쪽이면１점.」",
    L"커링스톤을 올려놓으면 ２점.」",
    L"파워게이지에 맞추어서",
    L"「마지막으로, 던질 세기를 정해.",
    L"던질 방향을 정했으면ａｈｉ로 결정.」",
    L"움직일  수 있어！",
    L"「이 때, 방향키의 상하로",
    L"방향키 좌우로 선택해.」",
    L"「이번엔, 던지는 방향（점선）을",
    L"움직이지 않으니까 잘 써야 해」",
    L"있는데, 그 것은 멈춘 곳에서",
    L"「가끔, 돌에 네 다리가 있은 것이",
    L"있으니가 사용할 타이밍을",
    L"「무거운돌, 가벼운돌, 여러가지 돌이",
    L"선택해.」",
    L"「우선, 커링스톤의 타입을",
    L"「으이...거의 이겼는데...」",
    L"「이 승부는, 질 수는 없어！」",
    L"「아직 졌다고 할 수는 없어！」",
    L"그럼, 게임 시작이다」",
    L"－２점 이니까 그 것만은",
    L"파란 선의 안쪽이면 １점.」",
    L"「마지막으로 던지는 세기를 정해.",
    L"움직일 수가 있어！",
    L"방향키의 좌우로 선택해.」",
    L"「다음은, 던지는 방향（점선）을",
    L"정말 잘 써야 해.」",
    L"정지한 곳에서 움직이지 않으니까,",
    L"「４개의 다리가 있는 돌은",
    L"그 것이 이기는 비결이야！」",
    L"적절하게 사용할 수가 있어.",
    L"「나는 천재니까, 여러 가지 돌을",
    L"종류를 정해야지.」",
    L"「그렇군, 우선 커링스톤의",
    L"C07긙긙긾깛C01",
    L"찾을수없는대사.txt",
    L"@@@@@````",
    L"+,*.-)(/",
    L"%& #\"$'!",
    L"71256348",
    L"%s\\%d-%d.wav",
    L"dhlptxtplh",
    L"C1을 알아들을 수 있게 되었다W",
    L"!#$.289:;<=CFGHIJKLNOPQRSTTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|",
    L"목표를　바꿈",
    L"C1을(를) 떨어뜨렸다W",
    L"C1이(가)RC7",
    L"C1가R부상을 입었다W",
    L"C7「장비한 기술」R",
    L"％만 감소하다 ！W",
    L"RC1을 익혔다W",
    L"Bits",
    L"현재 Bit %d",
    L"DoMove - kAssist",
    L"DoMove - kAll",
    L"DoMove - kDirect",
    L"EFEMcom11__setFunc",
    L"EFEMcom10__popV",
    L"EFEMcom0f__return",
    L"EFEMcom0e__funcS",
    L"EFEMcom0d__jsr",
    L"EFEMcom0c__pushA",
    L"EFEMcom0b__pushV",
    L"EFEMcom0a__pushC",
    L"EFEMcom09__goto",
    L"EFEMcom07__ifV",
    L"EFEMcomXX__null",
    L"EFEMcom04__setV",
    L"EFEMcom03__setT",
    L"EFEMcom02__rand",
    L"EFEMcom01__setV",
    L"EFEMcom00__setC",
    L"gFUNC_MAX",
    L"ID__CheckStatusTarget",
    L"ID__useMP",
    L"ID__GetGSPROJECTION",
    L"ID__objectOnOff",
    L"ID__draw_fade",
    L"ID__CheckHitSendIndex",
    L"ID__CheckHitAllEnemy",
    L"ID__CheckHitDirect",
    L"ID__turn_target",
    L"ID__ColorScreen",
    L"ID__draw_melt",
    L"ID_DrawAurolaFreeze",
    L"ID_MoveAurolaFreeze",
    L"ID_InitAurolaFreeze",
    L"ID__DrawConfuseStorm",
    L"ID__GetScreenProjection",
    L"ID__PaletteChange",
    L"ID__DrawTMDYXZScreen",
    L"ID__set_clut",
    L"ID__DrawTMD_YXZ",
    L"ID__GetSWAngle",
    L"ID__rand_TARGETp",
    L"ID__WorldToScreen",
    L"ID__AndVectorS",
    L"ID__DivVectorS",
    L"ID__MulVectorS",
    L"ID__draw_FT4_2",
    L"ID__reset_trans_root2",
    L"ID__draw_box",
    L"ID__FntPrint",
    L"ID__draw_grID",
    L"ID__draw_FT4",
    L"ID__reset_effect_view",
    L"ID__set_effect_view",
    L"ID__Model_GetJointPos",
    L"ID__set_infoParent",
    L"ID__draw_line",
    L"ID__Mul",
    L"ID__YXZ2XYZ",
    L"ID__Angle_ApplyYXZ",
    L"ID__Target_GetJointPos",
    L"ID__reset_trans_center",
    L"ID__ShiftRVector",
    L"ID__AndVector",
    L"ID__DivVector",
    L"ID__MulVector",
    L"ID__SubVector",
    L"ID__AddVector",
    L"ID__CopyVector",
    L"ID__GetVectorLength",
    L"ID__ChangeLastHitTarget",
    L"ID__angle_yxz2xyz",
    L"ID__CheckHitNoEvent",
    L"ID__vec2ang",
    L"ID__printf",
    L"ID__rand",
    L"ID__GetMedium",
    L"ID__rcos",
    L"ID__rsin",
    L"ID__get_MODELcollision",
    L"ID__leave3D_forPoint",
    L"ID__get_countANIM",
    L"ID__check_insIDeTARGETcircle",
    L"ID__reset_angle_forPoint",
    L"ID__reset_transModel",
    L"ID__draw_mask2",
    L"ID__draw_mask",
    L"ID__reset_trans_root",
    L"ID__play_SE",
    L"ID__set_ELECshock",
    L"ID__get_infoParent",
    L"ID__rotate2D",
    L"ID__draw_3dSP_2",
    L"ID__get_TARGETcollision",
    L"ID__draw_POLY44",
    L"ID__rot_trans_pears",
    L"ID__draw_SP4",
    L"ID__set_dust",
    L"ID__set_shadow",
    L"ID__get_TARGETp",
    L"ID__set_particle",
    L"ID__reset_objRGB",
    L"ID__get_targetPoint",
    L"ID__leave_forPoint",
    L"ID__div_vector",
    L"ID__draw_qube",
    L"ID__get_trans",
    L"ID__hit_target",
    L"ID__reset_transTarget",
    L"ID__rotZYX",
    L"ID__check_hit",
    L"ID__reset_trans",
    L"ID__draw_3dSP",
    L"ID__draw_obj",
    L"ID__set_object",
    L"ID__make_obj",
    L"ID__check_charcter",
    L"ETCDAT\\EX.TIM",
    L"ETCDAT\\EX.TMD",
    L"ETCDAT\\FEEL_EF.TMD",
    L"ETCHI\\MAHI.TMD",
    L"ETCDAT\\DEFEFF.TIM",
    L"ETCDAT\\DEFEFF.TMD",
    L"타겟　체인지",
    L"떨어져라",
    L"아이템을 주울 수 없다.",
    L"축하합니다",
    L"ETCHI\\LIFE.TIM",
    L"MOVIE\\EDR.wmv",
    L"MOVIE\\ED2.wmv",
    L"save\\%d.sav",
    L"28wÿO",
    L"%01d",
    L"%02d",
    L"%03d",
    L"%04d",
    L"%05d",
    L"%06d",
    L"?스??",
    L"스?파?",
    L"신통치 않다",
    L"나 일반적으로",
    L"아마추어",
    L"멜빵의 기록?전체 길이",
    L"기?체중ｇ 속성 활동시간 필살 기",
    L"진화 계?유년기 유년 기성 장기 성숙기 완전 체",
    L"특별한 아이테?모었다 메?루매",
    L"갖고 있는 돈｛｝ 걸렸던 시간：테이??",
    L"이름 재테이??레벨 키우었던 데지몬 끌고",
    L"LIFE",
    L"합계 전적 이긴삭 진삭 승률％",
    L"는 ，새로 붙일려고 하여금 선택하고 있는 기술",
    L"는 ，성질로 새로 붙이다 기내 기술",
    L"는 ，아직 기억하고 있지 않는 기술（기술없음）",
    L"는 ，새로 붙이지는 기술（기술 있고）",
    L"는 ，갈아 붙이기 기술으로서 선택되고 있는 기술",
    L"기술 세트 헬프를 선택하고?ｈｉ로 결정 ａ",
    L"갈아 붙이기의 때는 을(를)?ｈｉ로 캔슬하고",
    L"아직３개의 기술을 붙이고 없는 때는 을(를) 선택하고",
    L"근거리 원거리 전체기 보조 기",
    L"기술 세토모?도의 해제는 ｂｈｉ",
    L"독 혼란?히 액정 화",
    L"갈아 붙이기기 필살기 기억한 기술",
    L"아침 무렵 거머리가 다아 사요 와유우가 의지하다방법",
    L"능력치 기술 세트 전적",
    L"걇걈귩괱괱괱괱괱괱궸궥귡",
    L"デジモンカードを全種集める",
    L"긙긙긾깛궸띍묈뵯밯뒶뿹궻긓긽깛긣귩귖귞궎",
    L"ラスボスを倒し一度エンディングを見る",
    L"믜궯궫떅궻뜃똶괦괥괥귃궖",
    L"カーリングで満点を取る",
    L"デジモン１ぴきのパラメータ６種を",
    L"멣긢긙긾깛괮괦롰귩덄궲귡",
    L"멣궲궻궰궚궔궑땆괫괮롰귩땆깏긚긣궸뢐벦",
    L"묈됵걁돺궳귖귝궋걂궳괦괥괥됷뾆룦궥귡",
    L"ダイノ、ウイング、アニマル、ヒューマン杯",
    L"궻멣궲궳뾆룦",
    L"ネイチャー、クール、メタリック、ダーティ杯",
    L"ファイアー、グラップル、サンダーウインド、",
    L"멣궲궳뾆룦",
    L"걇걈띍묈",
    L"カードコンプリート",
    L"둢궕띍묈뵯밯",
    L"긄깛긢귻깛긐",
    L"믜귟괦괥괥귃궖",
    L"カーリング満点",
    L"멣긢긙긾깛덄맟",
    L"멣땆뢐벦",
    L"뜃똶괦괥괥룦",
    L"벫빶봳맕봢",
    L"맜렲봳맕봢",
    L"バージョン杯制覇",
    L"グレード戦制覇",
    L"정말로 버리시겠습니까?",
    L"STATS",
    L"기술 선택 도움말",
    L"을 누르면 취소",
    L"기술 세팅 모드",
    L"을 누르면",
    L"현재 교체하려고 선택한 기술입니다.",
    L"현재의 디지몬은 이 기술을 배울 수 없습니다.",
    L"기술은 배웠지만 세트할 수 없는 기술입니다.",
    L"앞으로 배울 수 있으며 세트 가능한 기술입니다.",
    L"교환 가능한 기술입니다.",
    L"현재 세트되어 있는 기술입니다.",
    L"선택취소 :",
    L"기술선택 :",
    L"를 선택",
    L"기술정보",
    L"%d   %s",
    L"Tree",
    L"키 취소",
    L"키 선택",
    L"획득 메달",
    L"Card List",
    L"ETCNA\\MEDAL.TMD",
    L"궼뷲딠궸궶궯궲궢귏궯궫갏",
    L"ETCDAT\\TAMA.TMD",
    L"(#(#",
    L"\"$$$\"",
    L"ÿÿÿÿ'()('-,-!\"!#)*(,+-",
    L"\"$\"#%#",
    L"ETCDAT\\FISHING2.TIM",
    L"ETCDAT\\FISHING.TIM",
    L"0123456789",
    L".TMD",
    L"DOOR\\DOOR",
    L"ETCDAT\\SEA.TMD",
    L"%dD,%d",
    L"ETCDAT\\SAO.TMD",
    L"실이 끊어져 버렸다",
    L"가 걸렸다!",
    L"..그러나, 가발이 꽉차서 갖을 수 없다",
    L"을(를) 매달아 올렸다",
    L"라도 가엽기 때문에 놓아주고 들 것 같다",
    L"전체길이 %d사이즈",
    L"굉장하다! 전체길이 %d사이즈",
    L"걸렸다!!!",
    L"아차! 너무 빨랐다",
    L"그래도 미끼는 그대로 있다.",
    L"아차! 너무 늦었다",
    L"미끼가 떨어져 나갔다.",
    L"뭔가 걸렸을려나?",
    L"%x::%s",
    L"DirectX 8.1버전이 설치되어 있으나 \"하드웨어 가속 Direct3D\"를 초기화 할 수 없습니다.",
    L"DirectX 8.1버전이 설치되어 있지 않습니다.",
    L"공격 력",
    L"방어 력",
    L"x|x|",
    L"회복 플로피",
    L"중회복 플로피",
    L"대회복 플로피",
    L"초회복 플로피",
    L"더블 플로피",
    L"종합 플로피",
    L"만능 플로피",
    L"이상방어 플로피",
    L"부활 플로피",
    L"완전부활 플로피",
    L"공격 플러그인",
    L"방어 플러그인",
    L"고속 플러그인",
    L"만능 플러그인",
    L"공격 플러그인Ｓ",
    L"방어 플러그인Ｓ",
    L"고속 플러그인Ｓ",
    L"오토파일럿",
    L"공격 티켓",
    L"방어 티켓",
    L"판단력 티켓",
    L"순발력 티켓",
    L"악마의 티켓Ａ",
    L"악마의 티켓Ｄ",
    L"악마의 티켓Ｅ",
    L"휴대용 화장실",
    L"연습 설명서",
    L"숙면베개",
    L"적을 피하는 부적",
    L"적을 부르는 종",
    L"건강샌들",
    L"커다란 고기",
    L"최고의 고기",
    L"연습효과 당근",
    L"연습효과 무우",
    L"디지 버섯",
    L"눈송이 버섯",
    L"고급 버섯",
    L"디지 도토리",
    L"파란사과",
    L"아세라로",
    L"황금 도토리",
    L"자연산 밤",
    L"맨드레이크",
    L"식용선인장",
    L"오렌지바나나",
    L"힘의 열매",
    L"튼튼 열매",
    L"날렵함의 열매",
    L"지혜의 열매",
    L"체력의 열매",
    L"정신력의 열매",
    L"디지 송사리",
    L"디지 붕어",
    L"디지 농어",
    L"검은 디지 농어",
    L"디지 메기",
    L"디지 가물치",
    L"상한 고기",
    L"이상한 버섯",
    L"회색 손톱",
    L"불꽃 조각",
    L"불타는 날개",
    L"강철 말발굽",
    L"흑백의 돌",
    L"강철 드릴",
    L"이빨 화석",
    L"검은 깃털",
    L"가시곤봉",
    L"빛나는 갈기",
    L"하얀 깃털",
    L"낡은 천조각",
    L"전기 링",
    L"무지개빛 피리",
    L"성스러운 뿔",
    L"무거운 투구",
    L"톱날 집게",
    L"유기 비료",
    L"자객의 지침서",
    L"용왕의 술",
    L"북극성의 표식",
    L"붉은 조개껍질",
    L"딱딱한 비늘",
    L"얼음수정",
    L"선글라스",
    L"금속 부품",
    L"죽음을 부르는 뼈",
    L"사이버 파츠",
    L"메가 핸드",
    L"메탈 아머",
    L"작은 창",
    L"사랑의 반창고",
    L"황금 바나나",
    L"수수께끼의 알",
    L"기적의 루비",
    L"딱정벌레 다이아",
    L"산호 부적",
    L"달빛의 거울",
    L"호수왕의 피리",
    L"싸구려 낚싯대",
    L"좋은 낚싯대",
    L"레오몬족의 석판",
    L"저택의 열쇠",
    L"톱니바퀴",
    L"초롱꽃  열매",
    L"피묻은 고기",
    L"냉장고의 열쇠",
    L"고대문자 해독기",
    L"기가 핸드",
    L"고귀한 갈기",
    L"메탈 바나나",
    L"*8;<=>",
    L"투기장 전투의 테마5",
    L"투기장 전투의 테마4",
    L"이벤트 전투의 테마",
    L"투기장 전투 테마3",
    L"투기장 전투 테마2",
    L"파트너 패배의 테마",
    L"파트너 승리의 테마",
    L"투기장 전투 테마1",
    L"상대 입장의 테마",
    L"파트너 입장의 테마",
    L"토너먼트 우승의 테마",
    L"토너먼트 승리의 테마",
    L"토너먼트 진행의 테마",
    L"시작의 마을의 테마 (밤)",
    L"시작의 마을의 테마 (낮)",
    L"라스트전투의 테마",
    L"무한 마운틴의 테마",
    L"비밀의 해안동굴의 테마",
    L"비트랜드의 테마 (밤)",
    L"비트랜드의 테마 (낮)",
    L"쓰레기의 산의 테마 (밤)",
    L"쓰레기의 산의 테마 (낮)",
    L"하수도의 테마",
    L"팩토리의 테마 (밤)",
    L"사실의 테마",
    L"장난감 저택의 테마",
    L"왈몬자에몬의 테마",
    L"미스 티밤의 테마",
    L"미스치츠리?주의 테?마",
    L"개골개골 습지의 테마 (밤)",
    L"개골개골 습지의 테마 (낮)",
    L"야조보호지역의 테마 (아래)",
    L"야조보호지역의 테마",
    L"컬링 의 테마",
    L"나 베개의 테마",
    L"프리즈 랜드의 테마 (밤)",
    L"프리즈 랜드의 테마 (낮)",
    L"고대 다이노의 테마2 (밤)",
    L"고대 다이노의 테마2 (낮)",
    L"고대 다이노의 테마1 (밤)",
    L"고대 다이노의 테마1 (낮)",
    L"선택의 숲의 테마 (밤)",
    L"선택의 숲의 테마 (낮)",
    L"레오몬의 테마",
    L"기어사반나의 테마 (밤)",
    L"기어사반나의 테마 (낮)",
    L"하수구의 테마",
    L"암흑 귀족의 저택의 테마",
    L"용암동굴의 테마",
    L"오가몬의 테마３",
    L"만물상의 테마",
    L"오가몬의 테마２",
    L"그레이트 캐년의 테마",
    L"오버델 묘지 테마",
    L"오가몬의 테마",
    L"트릴 터널의 테마",
    L"전망대산의 테마 (밤)",
    L"전망대산의 테마 (낮)",
    L"트로피칼 정글의 테마 (밤)",
    L"트로피칼 정글의 테마 (낮)",
    L"헤매지 않는 숲의 테마 (밤)",
    L"헤매지 않는 숲의 테마 (낮)",
    L"메탈에테몬으로 진화한다！",
    L"화이트레오몬으로 진화한다！",
    L"기가드라몬으로 진화한다！",
    L"고대문자를 읽을 수 있게된다！",
    L"냉장고를 여는 열쇠",
    L"암흑귀족 저택의 열쇠",
    L"레오몬의 선조가 남긴 석판",
    L"호수에서 낚시가되고, 잘 낚인다！",
    L"호수에서 낚시를 할 수있다！",
    L"시드라몬과의 우정의 정표",
    L"에어가루몬으로 진화한다！",
    L"메가시드라몬으로 진화한다！",
    L"헤라클레스캅테리몬으로 진화한다！",
    L"봉황몬으로 진화한다！",
    L"디지타몬으로 진화한다！",
    L"에테몬으로 진화한다！",
    L"베타몬으로 진화한다！",
    L"퍼펫몬으로 진화한다！",
    L"피콜몬으로 진화한다！",
    L"째리몬으로 진화한다！",
    L"메탈콩알몬으로 진화한다！",
    L"콩알몬으로 진화한다！",
    L"메가드라몬으로 진화한다！",
    L"안드로몬으로 진화한다！",
    L"스컬그레이몬으로 진화한다！",
    L"메탈그레이몬으로 진화한다！",
    L"모야몬으로 진화한다！",
    L"모털몬으로 진화한다！",
    L"프리지몬으로 진화한다！",
    L"가루몬으로 진화한다！",
    L"실러컨몬으로 진화한다！",
    L"쉘몬으로 진화한다！",
    L"고래몬으로 진화한다！",
    L"시드라몬으로 진화한다！",
    L"자객몬으로 진화한다！",
    L"베지몬으로 진화한다！",
    L"쿠가몬으로 진화한다！",
    L"캅테리몬으로 진화한다！",
    L"유니몬으로 진화한다！",
    L"꼬끼몬으로 진화한다！",
    L"에어드라몬으로 진화한다！",
    L"벼락몬으로 진화한다！",
    L"고스몬으로 진화한다！",
    L"엔젤몬으로 진화한다！",
    L"레오몬으로 진화한다！",
    L"우가몬으로 진화한다！",
    L"데블몬으로 진화한다！",
    L"티라노몬으로 진화한다！",
    L"두리몬으로 진화한다！",
    L"모노크로몬으로 진화한다！",
    L"켄터스몬으로　진화한다！",
    L"버드라몬으로 진화한다！",
    L"메라몬으로 진화한다！",
    L"그레이몬으로 진화한다！",
    L"먹을것．여러가지 좋은 효과가！",
    L"먹을것．기분이 좋아진다! 때론...",
    L"먹을것．일단 배는 부르지만...",
    L"먹을것．배가 엄청나게 부름。",
    L"먹을것．모든능력이 올라감！",
    L"먹을것．배가 매우 부름",
    L"먹을것．배가 적당히 부름",
    L"먹을것．배가 조금 부름",
    L"먹을것．다이어트에 좋다！",
    L"먹을것．배가 부르지만, 살도 많이찐다！",
    L"먹을것．비싸게 팔 수 있다！",
    L"먹을것．피로회복. 예의, 행복도 올라감！",
    L"먹을것．기분이 매우 좋아진다！",
    L"먹을것．잠시동안 연습 효과가 올라감！",
    L"먹을것．모든 능력이 올라감！",
    L"먹을것．예의가 매우 올라감",
    L"먹을것. 배가 아주 조금 부름",
    L"먹을것. 피로가 많이 풀린다！",
    L"먹을것. 잠시동안 연습 효과가 올라감！",
    L"먹을것. 배가 매우 부름",
    L"먹을것. 배가 적당히 부름",
    L"먹을것. 배가 조금 부름",
    L"가지고 걸으면 조금씩 회복. 뛰면 안됨！",
    L"가지고 있으면 적을 만나기 쉬워진다！",
    L"가지고 있으면 적을 피하기 쉬워진다！",
    L"가지고 있으면 잘때 회복력이 올라간다！",
    L"가지고 있으면 연습의 효과가 올라간다！",
    L"일회용　화장실．어디서나 안심！",
    L"방어력, 속도를 １００올린다.그러나...",
    L"공격력, 지능을 １００올린다.그러나...",
    L"방어력을 ５０올린다",
    L"공격력을 ５０올린다",
    L"마을로 순간이동한다！",
    L"지금 전투만 순발력이 많이 올라감",
    L"지금 전투만 방어력이 많이 올라감",
    L"지금 전투만 공격력이 많이 올라감",
    L"지금 전투만 모든능력이 올라감",
    L"지금 전투만 순발력이 올라감",
    L"지금 전투만 방어력이 올라감",
    L"지금 전투만 공격력이 올라감",
    L"상태이상,가사상태를 고치고,ＨＰ회복！",
    L"가사상태를 고치고,ＨＰ 절반 회복",
    L"전투중의 상태이상을 막는다！",
    L"독·마비·혼란·액정화를 고친다",
    L"하이메가브러스터",
    L"메일스트롬",
    L"그레이샬브러스트",
    L"크림존플레어",
    L"무한케논",
    L"절대영도펀치",
    L"볼케노스트라이크",
    L"버리어브르더츠",
    L"스파이럴소트",
    L"스파크링선더",
    L"시저암즈",
    L"프치화이어",
    L"포이즌아이비",
    L"페트러화이어",
    L"나이트메어신드롬",
    L"무한빈터",
    L"메테오윙",
    L"메가브러스터",
    L"러브·세레나데",
    L"야수왕권",
    L"제트아로",
    L"이가류수리검법",
    L"아이스아로",
    L"하이드로프렛샤",
    L"하이틴케논",
    L"뼈부메랑",
    L"호리숏트",
    L"헬즈핸드",
    L"헤븐즈너클",
    L"그라운드제로",
    L"기가디스트로이어",
    L"제노사이드어텍",
    L"에네르기범",
    L"일렉트릭스레드",
    L"드릴스핀",
    L"딧드리봄",
    L"싱거운　한숨",
    L"에어숏트",
    L"메지컬화이어",
    L"스피닝니들",
    L"스마일리봄",
    L"아브다쿠숀광선",
    L"전기충격비리링",
    L"폭스화이어",
    L"메가프레임",
    L"디스크로우",
    L"버닝휘스트",
    L"러블리어텍",
    L"헤비프레임",
    L"화이어브레스",
    L"엔가처킹",
    L"궁극운치지옥그림지도",
    L"엔가초킹",
    L"고속운치팔방투",
    L"분팔방투",
    L"거대운치팔방투",
    L"거대운치투",
    L"고속운치투",
    L"초악취분사",
    L"버스터다이브",
    L"메가톤펀치",
    L"다이너마이트킹",
    L"마하점프",
    L"워크라이",
    L"멋슬챠지",
    L"그린트렙",
    L"데인저스팅",
    L"포이즌크로우",
    L"찬파휴므",
    L"마스모포인섹트플레그",
    L"포이즌파우더",
    L"리버스프로그램",
    L"후리포텐셜",
    L"디리트프로그램",
    L"펄스레이저",
    L"메탈스프린더",
    L"올렌지빔",
    L"파워크레인",
    L"티어드롭",
    L"오로라프리즈",
    L"아쿠어메직",
    L"워터브리트",
    L"아이스니들",
    L"빈터브러스트",
    L"아이스스탓츄",
    L"기가프리즈",
    L"허리케인",
    L"콘퓨즈스톰",
    L"윈도우컷터",
    L"스터틱에렉트",
    L"메가로스파크",
    L"일렉트릭크라우드",
    L"스피닝숏트",
    L"선더저스티즈",
    L"멜트다운",
    L"인피니티번",
    L"히트웨이브",
    L"마그마범",
    L"레드인페르노",
    L"스핏트화이어",
    L"프로미넌스빔",
    L"화이어타워",
    L"UYVYYUY2DXT1DXT2DXT3DXT4DXT5F",
    L"픘YVY",
    L"?.vW@",
    L"p냄6^",
    L"dタ>P",
    L"f졒tf",
    L"t벩(뾁?",
    L"~請ｯ瓔?",
    L"뒎풭坂?",
    L"꼪옜뚺?",
    L"P꽴}쀴?",
    L"컐였쒘?",
    L"|s퓪孼?",
    L"hr퓣뗮?",
    L"@p엿聾?",
    L"U풶롢?",
    L"\\S왼汀?",
    L"|R퓯잂?",
    L"tE옌枚?",
    L"(C엣號?",
    L",@와昴?",
    L"l?ｿ}摂?",
    L";옌往?",
    L"P8왕群?",
    L"1욈叡?",
    L"\\0옐Φ?",
    L"t.웅祥?",
    L"`+퓠앏?",
    L"0'엣蟬?",
    L"綿앓낼?",
    L"漂풏鞭?",
    L"롻얽쎖?",
    L"찝쓺市?",
    L"뀀풒횐?",
    L"豆풝졸?",
    L"堊H옇?",
    L"鷺앝킷?",
    L"皇앤幷?",
    L"選쒼뙱?",
    L"겊았炙?",
    L"J횡6諛?",
    L"꽶앉餘?",
    L"뼽없옶?",
    L"戟푏푿?",
    L"쑘푐父?",
    L"융풓삮?",
    L"6늅2擊?",
    L"넯푂珩?",
    L"벼푒묠?",
    L"젳쐼묘?",
    L"p왍%윢?",
    L"p쑟&再?",
    L"崟,y｢?",
    L"z埓\"?｢?",
    L"릺야뮕?",
    L"컧풎풛?",
    L"떮v첏?",
    L"R꺘n쿃?",
    L"$|얻옑?",
    L"툂쓺넆?",
    L"Xr풏죻?",
    L"n푍핓?",
    L"@m푃뱮?",
    L"(i퐹퇂?",
    L"\\hｾ 兼?",
    L"dd애퀞?",
    L"쐁업닋?",
    L"_씬땻?",
    L"T[푕폁?",
    L"쁛엉뮁?",
    L"PV씸윆?",
    L",R푣콒?",
    L"|Q풆뎻?",
    L"|M암윂?",
    L"쟅푗퍕?",
    L"@E얏큾?",
    L"쭰었릩?",
    L"x@풆몜?",
    L"l<ｾ+莱?",
    L"9풌흫?",
    L"욶銓욶銓욶銓욶銓",
    L"/6柱O뱉튟뱉튟뱉튟밖",
    L"떵靜L민最7靜L민最7",
    L"a4,껠\"?껠\"?껠\"?껠\"?",
    L"?쩓j?,L",
    L"ｼCEu蹉ﾅQ胼KB",
    L"슇Y>t$7?*찒=",
    L"슇Y>t$7?",
    L"뤔<絿-=",
    L"-DTû!",
    L"ﾉ?X葵4X葵4X葵4X葵4h!\"4h!\"4h!\"4h!\"4三ｮ=三ｮ=三ｮ=三ｮ=tU",
    L"ｾ三ｮ=三ｮ=三ｮ=三ｮ=h!\"4h!\"4h!\"4h!\"4ﾛ",
    L"뤔<絿-=絿-=絿-=絿-=",
    L"w늿s3",
    L"ww333",
    L"뻣33뺙30",
    L";ｻ3;33",
    L";3뻣33",
    L";3333ｳ3333",
    L"3333",
    L"뻣뻣33;뺙0",
    L";뻣뻣뻣뺙",
};
static const size_t g_strings_count = 1809;
